
name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true

jobs:
  create:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Push Tag
      run: | 
            echo "version is ${{ github.event.inputs.version }}"
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            sed -i "/is_master/d" fxmanifest.lua
            sed -i "/^version/c\version '${{ github.event.inputs.version }}'" fxmanifest.lua
            git add .
            git commit -m "${{ github.event.inputs.version }}"
            git tag -a ${{ github.event.inputs.version }} -m "Version ${{ github.event.inputs.version }}"
            sed -i "/^version/ais_master 'yes'" fxmanifest.lua
            git add .
            git commit -m "Update Version"
            git push --follow-tags
